---
roles:

  # General Purpose Roles
  # =====================
  el-utils:
    provisioners:
      - type: shell
        inline: |
          yum -y install git

  # Puppet Specific Roles
  # =================
  r10k:
    provisioners:
      - type: shell
        inline: |
          repo=puppet-r10k
          git clone https://github.com/snemetz/${repo}.git
          cd ${repo}
          ./install.sh
          cd ..
          rm -rf ${repo}

